<?xml version="1.0" encoding="utf-8"?><Database Name="Te.ActivityFinder" Class="LocationDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=197.242.147.178;Initial Catalog=Te.ActivityFinder;User ID=teameffort" SettingsObjectName="Te.ActivityFinder.Dal.Properties.Settings" SettingsPropertyName="Te_ActivityFinderConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Location" Member="Locations">
    <Type Name="Location">
      <Column Name="LocationId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Town" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Street" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Suburb" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Latitude" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Longitude" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>